// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package otw

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OTWClient is the client API for OTW service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OTWClient interface {
	ListOtw(ctx context.Context, in *ListOTWPayload, opts ...grpc.CallOption) (*ListOTWResponse, error)
}

type oTWClient struct {
	cc grpc.ClientConnInterface
}

func NewOTWClient(cc grpc.ClientConnInterface) OTWClient {
	return &oTWClient{cc}
}

func (c *oTWClient) ListOtw(ctx context.Context, in *ListOTWPayload, opts ...grpc.CallOption) (*ListOTWResponse, error) {
	out := new(ListOTWResponse)
	err := c.cc.Invoke(ctx, "/samantra.services.otw.OTW/ListOtw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OTWServer is the server API for OTW service.
// All implementations must embed UnimplementedOTWServer
// for forward compatibility
type OTWServer interface {
	ListOtw(context.Context, *ListOTWPayload) (*ListOTWResponse, error)
	mustEmbedUnimplementedOTWServer()
}

// UnimplementedOTWServer must be embedded to have forward compatible implementations.
type UnimplementedOTWServer struct {
}

func (UnimplementedOTWServer) ListOtw(context.Context, *ListOTWPayload) (*ListOTWResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOtw not implemented")
}
func (UnimplementedOTWServer) mustEmbedUnimplementedOTWServer() {}

// UnsafeOTWServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OTWServer will
// result in compilation errors.
type UnsafeOTWServer interface {
	mustEmbedUnimplementedOTWServer()
}

func RegisterOTWServer(s grpc.ServiceRegistrar, srv OTWServer) {
	s.RegisterService(&OTW_ServiceDesc, srv)
}

func _OTW_ListOtw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOTWPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTWServer).ListOtw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/samantra.services.otw.OTW/ListOtw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTWServer).ListOtw(ctx, req.(*ListOTWPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// OTW_ServiceDesc is the grpc.ServiceDesc for OTW service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OTW_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "samantra.services.otw.OTW",
	HandlerType: (*OTWServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOtw",
			Handler:    _OTW_ListOtw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "samantra/services/otw_service/otw.proto",
}
