// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: trader_service.proto

package trader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TraderServiceClient is the client API for TraderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TraderServiceClient interface {
	TraderID(ctx context.Context, in *TraderIDPayload, opts ...grpc.CallOption) (*TraderIDResponse, error)
}

type traderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTraderServiceClient(cc grpc.ClientConnInterface) TraderServiceClient {
	return &traderServiceClient{cc}
}

func (c *traderServiceClient) TraderID(ctx context.Context, in *TraderIDPayload, opts ...grpc.CallOption) (*TraderIDResponse, error) {
	out := new(TraderIDResponse)
	err := c.cc.Invoke(ctx, "/samantra.services.trader.TraderService/TraderID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraderServiceServer is the server API for TraderService service.
// All implementations must embed UnimplementedTraderServiceServer
// for forward compatibility
type TraderServiceServer interface {
	TraderID(context.Context, *TraderIDPayload) (*TraderIDResponse, error)
	mustEmbedUnimplementedTraderServiceServer()
}

// UnimplementedTraderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTraderServiceServer struct {
}

func (UnimplementedTraderServiceServer) TraderID(context.Context, *TraderIDPayload) (*TraderIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TraderID not implemented")
}
func (UnimplementedTraderServiceServer) mustEmbedUnimplementedTraderServiceServer() {}

// UnsafeTraderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraderServiceServer will
// result in compilation errors.
type UnsafeTraderServiceServer interface {
	mustEmbedUnimplementedTraderServiceServer()
}

func RegisterTraderServiceServer(s grpc.ServiceRegistrar, srv TraderServiceServer) {
	s.RegisterService(&TraderService_ServiceDesc, srv)
}

func _TraderService_TraderID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraderIDPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServiceServer).TraderID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/samantra.services.trader.TraderService/TraderID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServiceServer).TraderID(ctx, req.(*TraderIDPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// TraderService_ServiceDesc is the grpc.ServiceDesc for TraderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TraderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "samantra.services.trader.TraderService",
	HandlerType: (*TraderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TraderID",
			Handler:    _TraderService_TraderID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trader_service.proto",
}
