// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.1
// source: samantra/services/rm2_services/warehouse/warehouse.proto

package warehouse

import (
	proto "github.com/golang/protobuf/proto"
	common "github.com/poommu-sp/public-exim-grpc-protocol.git/samantra/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Warehouse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LotNo       string                  `protobuf:"bytes,1,opt,name=lot_no,json=lotNo,proto3" json:"lot_no,omitempty"`
	ProductCode string                  `protobuf:"bytes,2,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	PlantId     int64                   `protobuf:"varint,3,opt,name=plant_id,json=plantId,proto3" json:"plant_id,omitempty"`
	Age         int64                   `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Total       *common.Amount          `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	Quantities  []*common.PlantQuantity `protobuf:"bytes,6,rep,name=quantities,proto3" json:"quantities,omitempty"`
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_samantra_services_rm2_services_warehouse_warehouse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_samantra_services_rm2_services_warehouse_warehouse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *Warehouse) GetLotNo() string {
	if x != nil {
		return x.LotNo
	}
	return ""
}

func (x *Warehouse) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *Warehouse) GetPlantId() int64 {
	if x != nil {
		return x.PlantId
	}
	return 0
}

func (x *Warehouse) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Warehouse) GetTotal() *common.Amount {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *Warehouse) GetQuantities() []*common.PlantQuantity {
	if x != nil {
		return x.Quantities
	}
	return nil
}

var File_samantra_services_rm2_services_warehouse_warehouse_proto protoreflect.FileDescriptor

var file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDesc = []byte{
	0x0a, 0x38, 0x73, 0x61, 0x6d, 0x61, 0x6e, 0x74, 0x72, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x72, 0x6d, 0x32, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x77, 0x61, 0x72, 0x65, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x73, 0x61, 0x6d, 0x61,
	0x6e, 0x74, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x72, 0x6d,
	0x32, 0x2e, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x1a, 0x1c, 0x73, 0x61, 0x6d,
	0x61, 0x6e, 0x74, 0x72, 0x61, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x01, 0x0a, 0x09, 0x57, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x74, 0x5f, 0x6e,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x74, 0x4e, 0x6f, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x2d,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x73, 0x61, 0x6d, 0x61, 0x6e, 0x74, 0x72, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3e, 0x0a,
	0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x61, 0x6d, 0x61, 0x6e, 0x74, 0x72, 0x61, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x69, 0x5a,
	0x67, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x74, 0x64,
	0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x2f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x73, 0x61, 0x6d, 0x61, 0x6e, 0x74, 0x72, 0x61, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72, 0x6d, 0x32, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x3b, 0x77,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDescOnce sync.Once
	file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDescData = file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDesc
)

func file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDescGZIP() []byte {
	file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDescOnce.Do(func() {
		file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDescData)
	})
	return file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDescData
}

var file_samantra_services_rm2_services_warehouse_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_samantra_services_rm2_services_warehouse_warehouse_proto_goTypes = []interface{}{
	(*Warehouse)(nil),            // 0: samantra.services.rm2.warehouse.Warehouse
	(*common.Amount)(nil),        // 1: samantra.common.Amount
	(*common.PlantQuantity)(nil), // 2: samantra.common.PlantQuantity
}
var file_samantra_services_rm2_services_warehouse_warehouse_proto_depIdxs = []int32{
	1, // 0: samantra.services.rm2.warehouse.Warehouse.total:type_name -> samantra.common.Amount
	2, // 1: samantra.services.rm2.warehouse.Warehouse.quantities:type_name -> samantra.common.PlantQuantity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_samantra_services_rm2_services_warehouse_warehouse_proto_init() }
func file_samantra_services_rm2_services_warehouse_warehouse_proto_init() {
	if File_samantra_services_rm2_services_warehouse_warehouse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_samantra_services_rm2_services_warehouse_warehouse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Warehouse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_samantra_services_rm2_services_warehouse_warehouse_proto_goTypes,
		DependencyIndexes: file_samantra_services_rm2_services_warehouse_warehouse_proto_depIdxs,
		MessageInfos:      file_samantra_services_rm2_services_warehouse_warehouse_proto_msgTypes,
	}.Build()
	File_samantra_services_rm2_services_warehouse_warehouse_proto = out.File
	file_samantra_services_rm2_services_warehouse_warehouse_proto_rawDesc = nil
	file_samantra_services_rm2_services_warehouse_warehouse_proto_goTypes = nil
	file_samantra_services_rm2_services_warehouse_warehouse_proto_depIdxs = nil
}
