// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: mail_service/mail_service.proto

package mail_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_service_mail_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_mail_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_mail_service_mail_service_proto_rawDescGZIP(), []int{0}
}

type SendApprovalMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To           []string `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Cc           []string `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	DocType      string   `protobuf:"bytes,3,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	DocNo        string   `protobuf:"bytes,4,opt,name=doc_no,json=docNo,proto3" json:"doc_no,omitempty"`
	RedirectLink string   `protobuf:"bytes,5,opt,name=redirect_link,json=redirectLink,proto3" json:"redirect_link,omitempty"`
	Status       int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Remark       string   `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Language     string   `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *SendApprovalMailRequest) Reset() {
	*x = SendApprovalMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_service_mail_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendApprovalMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendApprovalMailRequest) ProtoMessage() {}

func (x *SendApprovalMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_mail_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendApprovalMailRequest.ProtoReflect.Descriptor instead.
func (*SendApprovalMailRequest) Descriptor() ([]byte, []int) {
	return file_mail_service_mail_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendApprovalMailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendApprovalMailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendApprovalMailRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *SendApprovalMailRequest) GetDocNo() string {
	if x != nil {
		return x.DocNo
	}
	return ""
}

func (x *SendApprovalMailRequest) GetRedirectLink() string {
	if x != nil {
		return x.RedirectLink
	}
	return ""
}

func (x *SendApprovalMailRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendApprovalMailRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *SendApprovalMailRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_mail_service_mail_service_proto protoreflect.FileDescriptor

var file_mail_service_mail_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d,
	0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xdc, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x6e,
	0x64, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x02, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x64, 0x6f, 0x63, 0x4e, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x32, 0x5f, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x25, 0x2e, 0x6d, 0x61, 0x69,
	0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x74, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61,
	0x6c, 0x2f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x69, 0x74,
	0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x6d, 0x61,
	0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mail_service_mail_service_proto_rawDescOnce sync.Once
	file_mail_service_mail_service_proto_rawDescData = file_mail_service_mail_service_proto_rawDesc
)

func file_mail_service_mail_service_proto_rawDescGZIP() []byte {
	file_mail_service_mail_service_proto_rawDescOnce.Do(func() {
		file_mail_service_mail_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_mail_service_mail_service_proto_rawDescData)
	})
	return file_mail_service_mail_service_proto_rawDescData
}

var file_mail_service_mail_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mail_service_mail_service_proto_goTypes = []interface{}{
	(*Empty)(nil),                   // 0: mail_service.Empty
	(*SendApprovalMailRequest)(nil), // 1: mail_service.SendApprovalMailRequest
}
var file_mail_service_mail_service_proto_depIdxs = []int32{
	1, // 0: mail_service.MailService.SendApprovalMail:input_type -> mail_service.SendApprovalMailRequest
	0, // 1: mail_service.MailService.SendApprovalMail:output_type -> mail_service.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mail_service_mail_service_proto_init() }
func file_mail_service_mail_service_proto_init() {
	if File_mail_service_mail_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mail_service_mail_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_service_mail_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendApprovalMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mail_service_mail_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mail_service_mail_service_proto_goTypes,
		DependencyIndexes: file_mail_service_mail_service_proto_depIdxs,
		MessageInfos:      file_mail_service_mail_service_proto_msgTypes,
	}.Build()
	File_mail_service_mail_service_proto = out.File
	file_mail_service_mail_service_proto_rawDesc = nil
	file_mail_service_mail_service_proto_goTypes = nil
	file_mail_service_mail_service_proto_depIdxs = nil
}
